-- Backfill release_date values from egyptian_movies.csv using exact year-aware title matches.
-- Generated by scripts/generate_release_date_backfill.py.

BEGIN;
UPDATE movies SET release_date = '1952-05-12' WHERE title = 'قليل البخت' AND year = 1952; -- قليل البخت
UPDATE movies SET release_date = '2023-01-25' WHERE title = 'المطاريد' AND year = 2023; -- المطاريد
UPDATE movies SET release_date = '1954-03-01' WHERE title = 'صراع في الوادي' AND year = 1954; -- صراع في الوادي
UPDATE movies SET release_date = '1936-02-10' WHERE title = 'وداد' AND year = 1936; -- وداد
UPDATE movies SET release_date = '1950-10-23' WHERE title = 'أمير الانتقام' AND year = 1950; -- أمير الانتقام
UPDATE movies SET release_date = '2023-04-20' WHERE title = 'بعد الشر' AND year = 2023; -- بعد الشر
UPDATE movies SET release_date = '1955-04-04' WHERE title = 'موعد مع إبليس' AND year = 1955; -- موعد مع إبليس
UPDATE movies SET release_date = '1952-06-23' WHERE title = 'الأسطى حسن' AND year = 1952; -- الأسطى حسن
UPDATE movies SET release_date = '1950-11-20' WHERE title = 'بابا أمين' AND year = 1950; -- بابا أمين
UPDATE movies SET release_date = '1937-11-29' WHERE title = 'سلامة في خير' AND year = 1937; -- سلامة في خير
UPDATE movies SET release_date = '1951-01-10' WHERE title = 'ابن النيل' AND year = 1951; -- ابن النيل
UPDATE movies SET release_date = '1952-07-28' WHERE title = 'كأس العذاب' AND year = 1952; -- كأس العذاب
UPDATE movies SET release_date = '2023-06-28' WHERE title = 'تاج' AND year = 2023; -- تاج
UPDATE movies SET release_date = '1955-01-02' WHERE title = 'الله معنا' AND year = 1955; -- الله معنا
UPDATE movies SET release_date = '1942-10-01' WHERE title = 'علي بابا والأربعين حرامي' AND year = 1942; -- علي بابا والأربعين حرامي
UPDATE movies SET release_date = '2023-06-21' WHERE title = 'بيت الروبي' AND year = 2023; -- بيت الروبي
UPDATE movies SET release_date = '2023-06-26' WHERE title = 'البعبع' AND year = 2023; -- البعبع
UPDATE movies SET release_date = '1943-10-04' WHERE title = 'البؤساء' AND year = 1943; -- البؤساء
UPDATE movies SET release_date = '1954-12-06' WHERE title = 'حياة أو موت' AND year = 1954; -- حياة أو موت
UPDATE movies SET release_date = '1940-09-29' WHERE title = 'دنانير' AND year = 1940; -- دنانير
UPDATE movies SET release_date = '1952-08-28' WHERE title = 'سيدة القطار' AND year = 1952; -- سيدة القطار
UPDATE movies SET release_date = '1955-03-07' WHERE title = 'أيامنا الحلوة' AND year = 1955; -- أيامنا الحلوة
UPDATE movies SET release_date = '1953-04-06' WHERE title = 'عائشة' AND year = 1953; -- عائشة
UPDATE movies SET release_date = '1944-03-27' WHERE title = 'رصاصة فى القلب' AND year = 1944; -- رصاصة فى القلب
UPDATE movies SET release_date = '1951-02-19' WHERE title = 'أولاد الشوارع' AND year = 1951; -- أولاد الشوارع
UPDATE movies SET release_date = '1942-10-29' WHERE title = 'ابن البلد' AND year = 1942; -- ابن البلد
UPDATE movies SET release_date = '1954-10-18' WHERE title = 'جعلوني مجرما' AND year = 1954; -- جعلوني مجرما
UPDATE movies SET release_date = '1945-10-18' WHERE title = 'كازينو اللطافة' AND year = 1945; -- كازينو اللطافة
UPDATE movies SET release_date = '1943-10-17' WHERE title = 'الطريق المستقيم' AND year = 1943; -- الطريق المستقيم
UPDATE movies SET release_date = '2023-06-28' WHERE title = 'مستر إكس' AND year = 2023; -- مستر إكس
UPDATE movies SET release_date = '1952-12-22' WHERE title = 'إديني عقلك' AND year = 1952; -- إديني عقلك
UPDATE movies SET release_date = '1955-11-28' WHERE title = 'عصافير الجنة' AND year = 1955; -- عصافير الجنة
UPDATE movies SET release_date = '1941-01-06' WHERE title = 'سي عمر' AND year = 1941; -- سي عمر
UPDATE movies SET release_date = '2023-05-24' WHERE title = 'شوجر دادي' AND year = 2023; -- شوجر دادي
UPDATE movies SET release_date = '1949-01-03' WHERE title = 'أحبك أنت' AND year = 1949; -- أحبك أنت
UPDATE movies SET release_date = '1950-12-31' WHERE title = 'الصقر' AND year = 1950; -- الصقر
UPDATE movies SET release_date = '1942-02-11' WHERE title = 'عايدة' AND year = 1942; -- عايدة
UPDATE movies SET release_date = '1955-01-02' WHERE title = 'درب المهابيل' AND year = 1955; -- درب المهابيل
UPDATE movies SET release_date = '1955-01-21' WHERE title = 'مملكة النساء' AND year = 1955; -- مملكة النساء
UPDATE movies SET release_date = '1946-03-14' WHERE title = 'ضحايا المدنيّة' AND year = 1946; -- ضحايا المدنيّة
UPDATE movies SET release_date = '1949-12-19' WHERE title = 'ليلة العيد' AND year = 1949; -- ليلة العيد
UPDATE movies SET release_date = '1939-11-09' WHERE title = 'قيس وليلى' AND year = 1939; -- قيس وليلى
UPDATE movies SET release_date = '1952-01-01' WHERE title = 'الدم يحن' AND year = 1952; -- الدم يحن
UPDATE movies SET release_date = '1941-03-24' WHERE title = 'انتصار الشباب' AND year = 1941; -- انتصار الشباب
UPDATE movies SET release_date = '1942-01-01' WHERE title = 'أولاد الفقراء' AND year = 1942; -- أولاد الفقراء
UPDATE movies SET release_date = '1949-04-18' WHERE title = 'جواهر' AND year = 1949; -- جواهر
UPDATE movies SET release_date = '1950-08-14' WHERE title = 'ظلموني الناس' AND year = 1950; -- ظلموني الناس
UPDATE movies SET release_date = '1941-10-09' WHERE title = 'مصنع الزوجات' AND year = 1941; -- مصنع الزوجات
UPDATE movies SET release_date = '1948-12-13' WHERE title = 'رجل لا ينام' AND year = 1948; -- رجل لا ينام
UPDATE movies SET release_date = '1949-09-05' WHERE title = 'إجازه في جهنم' AND year = 1949; -- إجازه في جهنم
UPDATE movies SET release_date = '1955-05-23' WHERE title = 'أهل الهوى' AND year = 1955; -- أهل الهوى
UPDATE movies SET release_date = '1944-11-23' WHERE title = 'نور الدين والبحّاره الثلاثة' AND year = 1944; -- نور الدين والبحّاره الثلاثة
UPDATE movies SET release_date = '1955-03-21' WHERE title = 'بنات الليل' AND year = 1955; -- بنات الليل
UPDATE movies SET release_date = '1953-09-28' WHERE title = 'غلطة العمر' AND year = 1953; -- غلطة العمر
UPDATE movies SET release_date = '1950-04-03' WHERE title = 'قمر 14' AND year = 1950; -- قمر 14
UPDATE movies SET release_date = '1955-11-13' WHERE title = 'بحر الغرام' AND year = 1955; -- بحر الغرام
UPDATE movies SET release_date = '1951-11-19' WHERE title = 'لك يوم يا ظالم' AND year = 1951; -- لك يوم يا ظالم
UPDATE movies SET release_date = '1949-07-25' WHERE title = 'المرأة' AND year = 1949; -- المرأة
UPDATE movies SET release_date = '1954-04-19' WHERE title = 'أثار في الرمال' AND year = 1954; -- أثار في الرمال
UPDATE movies SET release_date = '1953-03-23' WHERE title = 'دهب' AND year = 1953; -- دهب
UPDATE movies SET release_date = '1955-04-11' WHERE title = 'أماني العمر' AND year = 1955; -- أماني العمر
UPDATE movies SET release_date = '1953-02-09' WHERE title = 'بنت الاكابر' AND year = 1953; -- بنت الاكابر
UPDATE movies SET release_date = '1954-12-20' WHERE title = 'إنسان غلبان' AND year = 1954; -- إنسان غلبان
UPDATE movies SET release_date = '1951-07-30' WHERE title = 'البنات شربات' AND year = 1951; -- البنات شربات
UPDATE movies SET release_date = '1952-02-21' WHERE title = 'الأستاذة فاطمة' AND year = 1952; -- الأستاذة فاطمة
UPDATE movies SET release_date = '1941-12-01' WHERE title = 'عريس من استنبول' AND year = 1941; -- عريس من استنبول
UPDATE movies SET release_date = '1944-12-10' WHERE title = 'غرام وانتقام' AND year = 1944; -- غرام وانتقام
UPDATE movies SET release_date = '1955-11-11' WHERE title = 'الميعاد' AND year = 1955; -- الميعاد
UPDATE movies SET release_date = '1953-04-19' WHERE title = 'عبيد المال' AND year = 1953; -- عبيد المال
UPDATE movies SET release_date = '1952-01-01' WHERE title = 'الأم القاتلة' AND year = 1952; -- الأم القاتلة
UPDATE movies SET release_date = '1948-10-04' WHERE title = 'الحب لا يموت' AND year = 1948; -- الحب لا يموت
UPDATE movies SET release_date = '1944-10-19' WHERE title = 'شهداء الغرام' AND year = 1944; -- شهداء الغرام
UPDATE movies SET release_date = '1948-01-15' WHERE title = 'الستات عفاريت' AND year = 1948; -- الستات عفاريت
UPDATE movies SET release_date = '1954-05-31' WHERE title = 'الأرض الطيبة' AND year = 1954; -- الأرض الطيبة
UPDATE movies SET release_date = '1953-06-08' WHERE title = 'حب في الظلام' AND year = 1953; -- حب في الظلام
UPDATE movies SET release_date = '1950-03-01' WHERE title = 'امرأة من نار' AND year = 1950; -- امرأة من نار
UPDATE movies SET release_date = '1954-12-27' WHERE title = 'إنتصار الحب' AND year = 1954; -- إنتصار الحب
UPDATE movies SET release_date = '1954-05-31' WHERE title = 'حسن ومرقص وكوهين' AND year = 1954; -- حسن ومرقص وكوهين
UPDATE movies SET release_date = '1953-06-09' WHERE title = 'بلال مؤذن الرسول' AND year = 1953; -- بلال مؤذن الرسول
UPDATE movies SET release_date = '2023-12-07' WHERE title = 'شماريخ' AND year = 2023; -- شماريخ
UPDATE movies SET release_date = '1953-01-01' WHERE title = 'حميدو' AND year = 1953; -- حميدو
UPDATE movies SET release_date = '1954-12-27' WHERE title = 'شيطان الصحراء' AND year = 1954; -- شيطان الصحراء
UPDATE movies SET release_date = '1951-06-02' WHERE title = 'فرجت' AND year = 1951; -- فرجت
UPDATE movies SET release_date = '1952-10-15' WHERE title = 'صورة الزفاف' AND year = 1952; -- صورة الزفاف
UPDATE movies SET release_date = '1941-03-03' WHERE title = 'إلى الأبد' AND year = 1941; -- إلى الأبد
UPDATE movies SET release_date = '2023-04-21' WHERE title = 'مغامرات كوكو' AND year = 2023; -- مغامرات كوكو
UPDATE movies SET release_date = '1955-10-15' WHERE title = 'الغائبة' AND year = 1955; -- الغائبة
UPDATE movies SET release_date = '1951-09-03' WHERE title = 'تعال سلم' AND year = 1951; -- تعال سلم
UPDATE movies SET release_date = '1941-10-01' WHERE title = 'عاصفة على الريف' AND year = 1941; -- عاصفة على الريف
UPDATE movies SET release_date = '1945-02-19' WHERE title = 'سفير جهنم' AND year = 1945; -- سفير جهنم
UPDATE movies SET release_date = '1953-04-16' WHERE title = 'تاجر الفضائح' AND year = 1953; -- تاجر الفضائح
UPDATE movies SET release_date = '1951-11-15' WHERE title = 'انتقام الحبيب' AND year = 1951; -- انتقام الحبيب
UPDATE movies SET release_date = '1948-11-01' WHERE title = 'عنبر' AND year = 1948; -- عنبر
UPDATE movies SET release_date = '1951-03-23' WHERE title = 'السبع أفندي' AND year = 1951; -- السبع أفندي
UPDATE movies SET release_date = '1955-01-10' WHERE title = 'إني راحلة' AND year = 1955; -- إني راحلة
UPDATE movies SET release_date = '1950-12-25' WHERE title = 'ست الحسن' AND year = 1950; -- ست الحسن
UPDATE movies SET release_date = '1953-04-30' WHERE title = 'حكم قراقوش' AND year = 1953; -- حكم قراقوش
UPDATE movies SET release_date = '1946-05-20' WHERE title = 'النائب العام' AND year = 1946; -- النائب العام
UPDATE movies SET release_date = '1939-03-09' WHERE title = 'في ليلة ممطرة' AND year = 1939; -- في ليلة ممطرة
UPDATE movies SET release_date = '1952-06-23' WHERE title = 'مسمار جحا' AND year = 1952; -- مسمار جحا
UPDATE movies SET release_date = '1953-11-23' WHERE title = 'ابن الحارة' AND year = 1953; -- ابن الحارة
UPDATE movies SET release_date = '1939-11-06' WHERE title = 'العزيمة' AND year = 1939; -- العزيمة
UPDATE movies SET release_date = '1954-04-19' WHERE title = 'شرف البنت' AND year = 1954; -- شرف البنت
UPDATE movies SET release_date = '1945-10-15' WHERE title = 'البني آدم' AND year = 1945; -- البني آدم
UPDATE movies SET release_date = '1952-05-01' WHERE title = 'زينب' AND year = 1952; -- زينب
UPDATE movies SET release_date = '1955-03-28' WHERE title = 'أغلى من عينيه' AND year = 1955; -- أغلى من عينيه
UPDATE movies SET release_date = '1942-09-04' WHERE title = 'بنت ذوات' AND year = 1942; -- بنت ذوات
UPDATE movies SET release_date = '1954-11-15' WHERE title = 'بنت البلد' AND year = 1954; -- بنت البلد
UPDATE movies SET release_date = '1946-10-28' WHERE title = 'لست ملاكاً' AND year = 1946; -- لست ملاكاً
UPDATE movies SET release_date = '1951-02-27' WHERE title = 'حكم القوي' AND year = 1951; -- حكم القوي
UPDATE movies SET release_date = '1954-07-19' WHERE title = 'أسعد الأيام' AND year = 1954; -- أسعد الأيام
UPDATE movies SET release_date = '1946-11-18' WHERE title = 'الطائشة' AND year = 1946; -- الطائشة
UPDATE movies SET release_date = '1949-12-29' WHERE title = 'بيومي أفندي' AND year = 1949; -- بيومي أفندي
UPDATE movies SET release_date = '1953-04-20' WHERE title = 'اشهدوا يا ناس' AND year = 1953; -- اشهدوا يا ناس
UPDATE movies SET release_date = '1945-04-12' WHERE title = 'القرش الأبيض' AND year = 1945; -- القرش الأبيض
UPDATE movies SET release_date = '1943-02-04' WHERE title = 'العامل' AND year = 1943; -- العامل
UPDATE movies SET release_date = '1942-02-11' WHERE title = 'الستات في خطر' AND year = 1942; -- الستات في خطر
UPDATE movies SET release_date = '1942-11-16' WHERE title = 'أحلام الشباب' AND year = 1942; -- أحلام الشباب
UPDATE movies SET release_date = '1954-01-01' WHERE title = 'حلاق بغداد' AND year = 1954; -- حلاق بغداد
UPDATE movies SET release_date = '1942-04-01' WHERE title = 'رباب' AND year = 1942; -- رباب
UPDATE movies SET release_date = '1940-05-06' WHERE title = 'قلب المرأة' AND year = 1940; -- قلب المرأة
UPDATE movies SET release_date = '1940-01-15' WHERE title = 'يوم سعيد' AND year = 1940; -- يوم سعيد
UPDATE movies SET release_date = '1955-07-25' WHERE title = 'رنة الخلخال' AND year = 1955; -- رنة الخلخال
UPDATE movies SET release_date = '1954-11-01' WHERE title = 'أبو الدهب' AND year = 1954; -- أبو الدهب
UPDATE movies SET release_date = '1955-02-07' WHERE title = 'عهد الهوى' AND year = 1955; -- عهد الهوى
UPDATE movies SET release_date = '1950-11-06' WHERE title = 'أيام شبابي' AND year = 1950; -- أيام شبابي
UPDATE movies SET release_date = '1953-08-17' WHERE title = 'بائعة الخبز' AND year = 1953; -- بائعة الخبز
UPDATE movies SET release_date = '1947-01-13' WHERE title = 'ضربة القدر' AND year = 1947; -- ضربة القدر
UPDATE movies SET release_date = '1953-01-02' WHERE title = 'لحن حبي' AND year = 1953; -- لحن حبي
UPDATE movies SET release_date = '1942-02-01' WHERE title = 'ممنوع الحب' AND year = 1942; -- ممنوع الحب
UPDATE movies SET release_date = '1953-03-23' WHERE title = 'شريك حياتى' AND year = 1953; -- شريك حياتى
UPDATE movies SET release_date = '1948-03-18' WHERE title = 'صاحبة العمارة' AND year = 1948; -- صاحبة العمارة
UPDATE movies SET release_date = '1952-10-13' WHERE title = 'السماء لا تنام' AND year = 1952; -- السماء لا تنام
UPDATE movies SET release_date = '1951-02-19' WHERE title = 'ليلة الحنة' AND year = 1951; -- ليلة الحنة
UPDATE movies SET release_date = '1954-05-16' WHERE title = 'دستة مناديل' AND year = 1954; -- دستة مناديل
UPDATE movies SET release_date = '1938-11-14' WHERE title = 'لاشين' AND year = 1938; -- لاشين
UPDATE movies SET release_date = '1944-12-21' WHERE title = 'شارع محمد علي' AND year = 1944; -- شارع محمد علي
UPDATE movies SET release_date = '1944-02-24' WHERE title = 'ليلى في الظلام' AND year = 1944; -- ليلى في الظلام
UPDATE movies SET release_date = '1947-03-16' WHERE title = 'حبيب العمر' AND year = 1947; -- حبيب العمر
UPDATE movies SET release_date = '1952-01-02' WHERE title = 'انتصار الإسلام' AND year = 1952; -- انتصار الإسلام
UPDATE movies SET release_date = '1950-02-06' WHERE title = 'المظلومة' AND year = 1950; -- المظلومة
UPDATE movies SET release_date = '1947-10-20' WHERE title = 'سلطانة الصحراء' AND year = 1947; -- سلطانة الصحراء
UPDATE movies SET release_date = '1949-09-22' WHERE title = 'كل بيت له راجل' AND year = 1949; -- كل بيت له راجل
UPDATE movies SET release_date = '1949-11-28' WHERE title = 'عفريتة هانم' AND year = 1949; -- عفريتة هانم
UPDATE movies SET release_date = '1954-10-18' WHERE title = 'حدث ذات ليلة' AND year = 1954; -- حدث ذات ليلة
UPDATE movies SET release_date = '2023-02-03' WHERE title = 'أنا لحبيبي' AND year = 2023; -- أنا لحبيبي
UPDATE movies SET release_date = '1954-07-25' WHERE title = 'الظلم حرام' AND year = 1954; -- الظلم حرام
UPDATE movies SET release_date = '1953-10-12' WHERE title = 'السيد البدوي' AND year = 1953; -- السيد البدوي
UPDATE movies SET release_date = '1954-10-11' WHERE title = 'الستات ما يعرفوش يكدبوا' AND year = 1954; -- الستات ما يعرفوش يكدبوا
UPDATE movies SET release_date = '1949-04-29' WHERE title = 'عقبال البكاري' AND year = 1949; -- عقبال البكاري
UPDATE movies SET release_date = '1953-04-20' WHERE title = 'أرض الأبطال' AND year = 1953; -- أرض الأبطال
UPDATE movies SET release_date = '1953-11-03' WHERE title = 'ظلموني الحبايب' AND year = 1953; -- ظلموني الحبايب
UPDATE movies SET release_date = '1944-01-01' WHERE title = 'برلنتي' AND year = 1944; -- برلنتي
UPDATE movies SET release_date = '1954-10-14' WHERE title = 'دلوني يا ناس' AND year = 1954; -- دلوني يا ناس
UPDATE movies SET release_date = '1947-10-06' WHERE title = 'قلبي دليلي' AND year = 1947; -- قلبي دليلي
UPDATE movies SET release_date = '1943-01-01' WHERE title = 'جوهرة' AND year = 1943; -- جوهرة
UPDATE movies SET release_date = '1937-01-02' WHERE title = 'ليلي بنت الصحراء' AND year = 1937; -- ليلي بنت الصحراء
UPDATE movies SET release_date = '1953-04-16' WHERE title = 'طريق السعادة' AND year = 1953; -- طريق السعادة
UPDATE movies SET release_date = '1951-12-31' WHERE title = 'أسرار الناس' AND year = 1951; -- أسرار الناس
UPDATE movies SET release_date = '1948-01-01' WHERE title = 'المليونيرة الصغيرة' AND year = 1948; -- المليونيرة الصغيرة
UPDATE movies SET release_date = '1950-12-11' WHERE title = 'ياسمين' AND year = 1950; -- ياسمين
UPDATE movies SET release_date = '1955-07-25' WHERE title = 'الجسد' AND year = 1955; -- الجسد
UPDATE movies SET release_date = '1955-07-23' WHERE title = 'إسماعيل يس في الجيش' AND year = 1955; -- إسماعيل يس في الجيش
UPDATE movies SET release_date = '1947-04-07' WHERE title = 'غروب' AND year = 1947; -- غروب
UPDATE movies SET release_date = '1952-01-01' WHERE title = 'أموال اليتامى' AND year = 1952; -- أموال اليتامى
UPDATE movies SET release_date = '1954-05-31' WHERE title = 'عفريتة إسماعيل يس' AND year = 1954; -- عفريتة إسماعيل يس
UPDATE movies SET release_date = '1949-11-07' WHERE title = 'إوعى المحفظة' AND year = 1949; -- إوعى المحفظة
UPDATE movies SET release_date = '1952-06-09' WHERE title = 'من أين لك هذا' AND year = 1952; -- من أين لك هذا
UPDATE movies SET release_date = '1950-07-07' WHERE title = 'المليونير' AND year = 1950; -- المليونير
UPDATE movies SET release_date = '1942-01-01' WHERE title = 'بحبح في بغداد' AND year = 1942; -- بحبح في بغداد
UPDATE movies SET release_date = '1949-02-07' WHERE title = 'نادية' AND year = 1949; -- نادية
UPDATE movies SET release_date = '1945-12-31' WHERE title = 'قصة غرام' AND year = 1945; -- قصة غرام
UPDATE movies SET release_date = '1953-12-16' WHERE title = 'عفريت عم عبده' AND year = 1953; -- عفريت عم عبده
UPDATE movies SET release_date = '1942-05-01' WHERE title = 'محطة الأنس' AND year = 1942; -- محطة الأنس
UPDATE movies SET release_date = '1948-12-27' WHERE title = 'خيال إمراة' AND year = 1948; -- خيال إمراة
UPDATE movies SET release_date = '1950-12-29' WHERE title = 'اخلاق للبيع' AND year = 1950; -- اخلاق للبيع
UPDATE movies SET release_date = '1947-11-03' WHERE title = 'عودة الغائب' AND year = 1947; -- عودة الغائب
UPDATE movies SET release_date = '1954-04-05' WHERE title = 'الحياة الحب' AND year = 1954; -- الحياة الحب
UPDATE movies SET release_date = '2023-04-21' WHERE title = 'رمسيس باريس' AND year = 2023; -- رمسيس باريس
UPDATE movies SET release_date = '1942-04-02' WHERE title = 'ليلى' AND year = 1942; -- ليلى
UPDATE movies SET release_date = '1947-02-03' WHERE title = 'غني حرب' AND year = 1947; -- غني حرب
UPDATE movies SET release_date = '1940-02-08' WHERE title = 'تحت السلاح' AND year = 1940; -- تحت السلاح
UPDATE movies SET release_date = '1951-11-22' WHERE title = 'الدنيا حلوة' AND year = 1951; -- الدنيا حلوة
UPDATE movies SET release_date = '1941-02-01' WHERE title = 'ليلى بنت الريف' AND year = 1941; -- ليلى بنت الريف
UPDATE movies SET release_date = '1948-06-10' WHERE title = 'مغامرات عنتر وعبلة' AND year = 1948; -- مغامرات عنتر وعبلة
UPDATE movies SET release_date = '1955-03-01' WHERE title = 'لحن الوفاء' AND year = 1955; -- لحن الوفاء
UPDATE movies SET release_date = '1948-12-06' WHERE title = 'ليلى العامرية' AND year = 1948; -- ليلى العامرية
UPDATE movies SET release_date = '1951-04-09' WHERE title = 'ظهور الإسلام' AND year = 1951; -- ظهور الإسلام
UPDATE movies SET release_date = '1954-10-04' WHERE title = 'الأستاذ شرف' AND year = 1954; -- الأستاذ شرف
UPDATE movies SET release_date = '1946-04-25' WHERE title = 'ملكة الجمال' AND year = 1946; -- ملكة الجمال
UPDATE movies SET release_date = '1954-12-26' WHERE title = 'عروسة المولد' AND year = 1954; -- عروسة المولد
UPDATE movies SET release_date = '1950-01-01' WHERE title = 'دموع الفرح' AND year = 1950; -- دموع الفرح
UPDATE movies SET release_date = '1948-11-01' WHERE title = 'فتاه من فلسطين' AND year = 1948; -- فتاه من فلسطين
UPDATE movies SET release_date = '1945-11-19' WHERE title = 'جمال ودلال' AND year = 1945; -- جمال ودلال
UPDATE movies SET release_date = '1952-12-14' WHERE title = 'مصطفى كامل' AND year = 1952; -- مصطفى كامل
UPDATE movies SET release_date = '1950-10-09' WHERE title = 'قسمة ونصيب' AND year = 1950; -- قسمة ونصيب
UPDATE movies SET release_date = '1947-04-07' WHERE title = 'شادية الوادي' AND year = 1947; -- شادية الوادي
UPDATE movies SET release_date = '2023-01-18' WHERE title = 'اخي فوق الشجرة' AND year = 2023; -- اخي فوق الشجرة
UPDATE movies SET release_date = '1948-05-07' WHERE title = 'طلاق سعاد هانم' AND year = 1948; -- طلاق سعاد هانم
UPDATE movies SET release_date = '1929-04-25' WHERE title = 'بنت النيل' AND year = 1929; -- بنت النيل
UPDATE movies SET release_date = '1934-03-23' WHERE title = 'ياقوت' AND year = 1934; -- ياقوت
UPDATE movies SET release_date = '1955-10-30' WHERE title = 'ثورة المدينة' AND year = 1955; -- ثورة المدينة
UPDATE movies SET release_date = '1944-03-13' WHERE title = 'ليلي البدوية' AND year = 1944; -- ليلي البدوية
UPDATE movies SET release_date = '1947-05-12' WHERE title = 'العقل في أجازة' AND year = 1947; -- العقل في أجازة
UPDATE movies SET release_date = '1954-02-08' WHERE title = 'أقوى من الحب' AND year = 1954; -- أقوى من الحب
UPDATE movies SET release_date = '1952-02-21' WHERE title = 'ماتقولش لحد' AND year = 1952; -- ماتقولش لحد
UPDATE movies SET release_date = '1954-04-05' WHERE title = 'بنت الجيران' AND year = 1954; -- بنت الجيران
UPDATE movies SET release_date = '1952-12-01' WHERE title = 'حلال عليك' AND year = 1952; -- حلال عليك
UPDATE movies SET release_date = '1948-05-17' WHERE title = 'البوسطجي' AND year = 1948; -- البوسطجي
UPDATE movies SET release_date = '1943-03-04' WHERE title = 'كليوباترا' AND year = 1943; -- كليوباترا
UPDATE movies SET release_date = '1949-09-26' WHERE title = 'الستات كده' AND year = 1949; -- الستات كده
UPDATE movies SET release_date = '1955-01-01' WHERE title = 'كابتن مصر' AND year = 1955; -- كابتن مصر
UPDATE movies SET release_date = '1946-12-23' WHERE title = 'أحمر شفايف' AND year = 1946; -- أحمر شفايف
UPDATE movies SET release_date = '1945-11-20' WHERE title = 'ابن الشرق' AND year = 1945; -- ابن الشرق
UPDATE movies SET release_date = '1942-12-04' WHERE title = 'العريس الخامس' AND year = 1942; -- العريس الخامس
UPDATE movies SET release_date = '1949-01-01' WHERE title = 'سر الأميرة' AND year = 1949; -- سر الأميرة
UPDATE movies SET release_date = '1947-10-27' WHERE title = 'أبو حلموس' AND year = 1947; -- أبو حلموس
UPDATE movies SET release_date = '1952-07-23' WHERE title = 'زمن العجائب' AND year = 1952; -- زمن العجائب
UPDATE movies SET release_date = '1953-10-26' WHERE title = 'الحموات الفاتنات' AND year = 1953; -- الحموات الفاتنات
UPDATE movies SET release_date = '1946-12-20' WHERE title = 'الملاك الأبيض' AND year = 1946; -- الملاك الأبيض
UPDATE movies SET release_date = '1932-03-14' WHERE title = 'أولاد الذوات' AND year = 1932; -- أولاد الذوات
UPDATE movies SET release_date = '1953-01-26' WHERE title = 'حظك هذا الاسبوع' AND year = 1953; -- حظك هذا الاسبوع
UPDATE movies SET release_date = '1947-11-17' WHERE title = 'حمامة السلام' AND year = 1947; -- حمامة السلام
UPDATE movies SET release_date = '1948-01-05' WHERE title = 'الهوى والشباب' AND year = 1948; -- الهوى والشباب
UPDATE movies SET release_date = '1944-10-09' WHERE title = 'سيف الجلاد' AND year = 1944; -- سيف الجلاد
UPDATE movies SET release_date = '1945-03-05' WHERE title = 'الآنسه بوسه' AND year = 1945; -- الآنسه بوسه
UPDATE movies SET release_date = '1944-09-18' WHERE title = 'وحيدة' AND year = 1944; -- وحيدة
UPDATE movies SET release_date = '1950-09-01' WHERE title = 'بابا عريس' AND year = 1950; -- بابا عريس
UPDATE movies SET release_date = '1950-05-01' WHERE title = 'أفراح' AND year = 1950; -- أفراح
UPDATE movies SET release_date = '1950-11-27' WHERE title = 'معركة الحياة' AND year = 1950; -- معركة الحياة
UPDATE movies SET release_date = '1955-10-31' WHERE title = 'حب ودموع' AND year = 1955; -- حب ودموع
UPDATE movies SET release_date = '1950-11-12' WHERE title = 'آخر كدبة' AND year = 1950; -- آخر كدبة
UPDATE movies SET release_date = '1951-04-02' WHERE title = 'سماعة التليفون' AND year = 1951; -- سماعة التليفون
UPDATE movies SET release_date = '2023-04-21' WHERE title = 'ابن الحاج احمد' AND year = 2023; -- ابن الحاج احمد
UPDATE movies SET release_date = '1953-01-01' WHERE title = 'الدنيا لما تضحك' AND year = 1953; -- الدنيا لما تضحك
UPDATE movies SET release_date = '2023-01-04' WHERE title = 'شلبي' AND year = 2023; -- شلبي
UPDATE movies SET release_date = '1943-12-24' WHERE title = 'حب من السماء' AND year = 1943; -- حب من السماء
UPDATE movies SET release_date = '1954-10-04' WHERE title = 'الحقوني بالمأذون' AND year = 1954; -- الحقوني بالمأذون
UPDATE movies SET release_date = '1943-07-15' WHERE title = 'قضية اليوم' AND year = 1943; -- قضية اليوم
UPDATE movies SET release_date = '1946-10-28' WHERE title = 'ليلى بنت الأغنياء' AND year = 1946; -- ليلى بنت الأغنياء
UPDATE movies SET release_date = '1944-09-11' WHERE title = 'حنان' AND year = 1944; -- حنان
UPDATE movies SET release_date = '1951-04-05' WHERE title = 'حبيبتي سوسو' AND year = 1951; -- حبيبتي سوسو
UPDATE movies SET release_date = '1951-04-12' WHERE title = 'ضحيت غرامي' AND year = 1951; -- ضحيت غرامي
UPDATE movies SET release_date = '1950-03-27' WHERE title = 'فلفل' AND year = 1950; -- فلفل
UPDATE movies SET release_date = '1945-10-01' WHERE title = 'شهر العسل' AND year = 1945; -- شهر العسل
UPDATE movies SET release_date = '1942-01-01' WHERE title = 'خفايا الدنيا' AND year = 1942; -- خفايا الدنيا
UPDATE movies SET release_date = '1950-04-10' WHERE title = 'الزوجه السابعه' AND year = 1950; -- الزوجه السابعه
UPDATE movies SET release_date = '1950-03-06' WHERE title = 'البطل' AND year = 1950; -- البطل
UPDATE movies SET release_date = '1941-04-10' WHERE title = 'امرأة خطرة' AND year = 1941; -- امرأة خطرة
UPDATE movies SET release_date = '1948-03-09' WHERE title = 'حياة حائرة' AND year = 1948; -- حياة حائرة
UPDATE movies SET release_date = '1954-03-07' WHERE title = 'خطف مراتي' AND year = 1954; -- خطف مراتي
UPDATE movies SET release_date = '1951-09-02' WHERE title = 'شباك حبيبي' AND year = 1951; -- شباك حبيبي
UPDATE movies SET release_date = '1951-12-03' WHERE title = 'ليلة غرام' AND year = 1951; -- ليلة غرام
UPDATE movies SET release_date = '1951-04-19' WHERE title = 'خدعني أبي' AND year = 1951; -- خدعني أبي
UPDATE movies SET release_date = '1952-02-21' WHERE title = 'بيت النتاش' AND year = 1952; -- بيت النتاش
UPDATE movies SET release_date = '1945-10-09' WHERE title = 'أحلاهم' AND year = 1945; -- أحلاهم
UPDATE movies SET release_date = '1947-01-06' WHERE title = 'لبناني في الجامعة' AND year = 1947; -- لبناني في الجامعة
UPDATE movies SET release_date = '1951-10-08' WHERE title = 'حبيب الروح' AND year = 1951; -- حبيب الروح
UPDATE movies SET release_date = '2023-04-20' WHERE title = 'ساعة إجابة' AND year = 2023; -- ساعة إجابة
UPDATE movies SET release_date = '1943-01-11' WHERE title = 'رابحة' AND year = 1943; -- رابحة
UPDATE movies SET release_date = '2023-08-02' WHERE title = 'ع الزيرو' AND year = 2023; -- ع الزيرو
UPDATE movies SET release_date = '1941-10-16' WHERE title = 'ليلى بنت مدارس' AND year = 1941; -- ليلى بنت مدارس
UPDATE movies SET release_date = '1954-01-04' WHERE title = 'تاكسي الغرام' AND year = 1954; -- تاكسي الغرام
UPDATE movies SET release_date = '1948-12-20' WHERE title = 'نحو المجد' AND year = 1948; -- نحو المجد
UPDATE movies SET release_date = '1951-11-22' WHERE title = 'أشكى لمين' AND year = 1951; -- أشكى لمين
UPDATE movies SET release_date = '1939-01-23' WHERE title = 'الدكتور' AND year = 1939; -- الدكتور
UPDATE movies SET release_date = '1940-01-18' WHERE title = 'الباشمقاول' AND year = 1940; -- الباشمقاول
UPDATE movies SET release_date = '1930-04-09' WHERE title = 'زينب' AND year = 1930; -- زينب
UPDATE movies SET release_date = '1943-01-18' WHERE title = 'من فات قديمه' AND year = 1943; -- من فات قديمه
UPDATE movies SET release_date = '2023-01-25' WHERE title = 'إتنين للإيجار' AND year = 2023; -- إتنين للإيجار
UPDATE movies SET release_date = '1950-07-17' WHERE title = 'جوز الأربعة' AND year = 1950; -- جوز الأربعة
UPDATE movies SET release_date = '1948-09-13' WHERE title = 'الريف الحزين' AND year = 1948; -- الريف الحزين
UPDATE movies SET release_date = '1955-01-02' WHERE title = 'نهارك سعيد' AND year = 1955; -- نهارك سعيد
UPDATE movies SET release_date = '1955-05-23' WHERE title = 'تار بايت' AND year = 1955; -- تار بايت
UPDATE movies SET release_date = '1952-07-01' WHERE title = 'آمال' AND year = 1952; -- آمال
UPDATE movies SET release_date = '1945-03-26' WHERE title = 'ليلة الجمعة' AND year = 1945; -- ليلة الجمعة
UPDATE movies SET release_date = '1955-11-21' WHERE title = 'شاطئ الذكريات' AND year = 1955; -- شاطئ الذكريات
UPDATE movies SET release_date = '1943-03-14' WHERE title = 'بنت الشيخ' AND year = 1943; -- بنت الشيخ
UPDATE movies SET release_date = '1928-01-25' WHERE title = 'قبلة في الصحراء' AND year = 1928; -- قبلة في الصحراء
UPDATE movies SET release_date = '1949-04-28' WHERE title = 'الليل لنا' AND year = 1949; -- الليل لنا
UPDATE movies SET release_date = '2023-04-21' WHERE title = 'يوم 13' AND year = 2023; -- يوم 13
UPDATE movies SET release_date = '1951-12-10' WHERE title = 'الصبر جميل' AND year = 1951; -- الصبر جميل
UPDATE movies SET release_date = '1946-09-30' WHERE title = 'راوية' AND year = 1946; -- راوية
UPDATE movies SET release_date = '1951-04-30' WHERE title = 'الشرف غالي' AND year = 1951; -- الشرف غالي
UPDATE movies SET release_date = '1951-10-01' WHERE title = 'حماتي قنبلة ذرية' AND year = 1951; -- حماتي قنبلة ذرية
UPDATE movies SET release_date = '1953-07-20' WHERE title = 'لسانك حصانك' AND year = 1953; -- لسانك حصانك
UPDATE movies SET release_date = '1952-07-07' WHERE title = 'المساكين' AND year = 1952; -- المساكين
UPDATE movies SET release_date = '1942-02-11' WHERE title = 'ابن الصحراء' AND year = 1942; -- ابن الصحراء
UPDATE movies SET release_date = '1946-01-28' WHERE title = 'دنيا' AND year = 1946; -- دنيا
UPDATE movies SET release_date = '1950-04-02' WHERE title = 'بلدي وخفة' AND year = 1950; -- بلدي وخفة
UPDATE movies SET release_date = '1949-04-28' WHERE title = 'المرأة شيطان' AND year = 1949; -- المرأة شيطان
UPDATE movies SET release_date = '1948-01-01' WHERE title = 'أميرة الجزيرة' AND year = 1948; -- أميرة الجزيرة
UPDATE movies SET release_date = '1945-11-05' WHERE title = 'أميرة الأحلام' AND year = 1945; -- أميرة الأحلام
UPDATE movies SET release_date = '1944-06-04' WHERE title = 'الأبرياء' AND year = 1944; -- الأبرياء
UPDATE movies SET release_date = '1949-04-04' WHERE title = 'مبروك عليكي' AND year = 1949; -- مبروك عليكي
UPDATE movies SET release_date = '1951-05-07' WHERE title = 'آدم وحواء' AND year = 1951; -- آدم وحواء
UPDATE movies SET release_date = '1933-07-17' WHERE title = 'الزواج' AND year = 1933; -- الزواج
UPDATE movies SET release_date = '1940-10-17' WHERE title = 'رجل بين امرأتين' AND year = 1940; -- رجل بين امرأتين
UPDATE movies SET release_date = '1951-09-13' WHERE title = 'فتاة السيرك' AND year = 1951; -- فتاة السيرك
UPDATE movies SET release_date = '1955-10-15' WHERE title = 'ليالى الحب' AND year = 1955; -- ليالى الحب
UPDATE movies SET release_date = '1953-10-01' WHERE title = 'ابن ذوات' AND year = 1953; -- ابن ذوات
UPDATE movies SET release_date = '1947-10-05' WHERE title = 'القناع الأحمر' AND year = 1947; -- القناع الأحمر
UPDATE movies SET release_date = '1954-04-29' WHERE title = 'علشان عيونك' AND year = 1954; -- علشان عيونك
UPDATE movies SET release_date = '1952-10-30' WHERE title = 'ظلمت روحى' AND year = 1952; -- ظلمت روحى
UPDATE movies SET release_date = '1953-01-01' WHERE title = 'بين قلبين' AND year = 1953; -- بين قلبين
UPDATE movies SET release_date = '1951-05-02' WHERE title = 'جزيرة الأحلام' AND year = 1951; -- جزيرة الأحلام
UPDATE movies SET release_date = '1954-02-02' WHERE title = 'جنون الحب' AND year = 1954; -- جنون الحب
UPDATE movies SET release_date = '1954-03-29' WHERE title = 'الفارس الأسود' AND year = 1954; -- الفارس الأسود
UPDATE movies SET release_date = '1949-01-01' WHERE title = 'أسير العيون' AND year = 1949; -- أسير العيون
UPDATE movies SET release_date = '1946-10-14' WHERE title = 'سر أبي' AND year = 1946; -- سر أبي
UPDATE movies SET release_date = '1952-12-15' WHERE title = 'لحن الخلود' AND year = 1952; -- لحن الخلود
UPDATE movies SET release_date = '1948-10-07' WHERE title = 'الحلقة المفقودة' AND year = 1948; -- الحلقة المفقودة
UPDATE movies SET release_date = '1945-09-30' WHERE title = 'أول الشهر' AND year = 1945; -- أول الشهر
UPDATE movies SET release_date = '1955-01-10' WHERE title = 'نحن بشر' AND year = 1955; -- نحن بشر
UPDATE movies SET release_date = '1951-12-17' WHERE title = 'قطر الندى' AND year = 1951; -- قطر الندى
UPDATE movies SET release_date = '1948-03-29' WHERE title = 'فوق السحاب' AND year = 1948; -- فوق السحاب
UPDATE movies SET release_date = '1946-01-01' WHERE title = 'أول نظرة' AND year = 1946; -- أول نظرة
UPDATE movies SET release_date = '1947-03-03' WHERE title = 'ليالى الأنس' AND year = 1947; -- ليالى الأنس
UPDATE movies SET release_date = '1954-03-01' WHERE title = 'بنات حواء' AND year = 1954; -- بنات حواء
UPDATE movies SET release_date = '1945-04-09' WHERE title = 'سلامة' AND year = 1945; -- سلامة
UPDATE movies SET release_date = '1946-04-01' WHERE title = 'أصحاب السعادة' AND year = 1946; -- أصحاب السعادة
UPDATE movies SET release_date = '1940-10-31' WHERE title = 'صرخة في الليل' AND year = 1940; -- صرخة في الليل
UPDATE movies SET release_date = '1940-03-01' WHERE title = 'حياة الظلام' AND year = 1940; -- حياة الظلام
UPDATE movies SET release_date = '1950-02-20' WHERE title = 'شاطئ الغرام' AND year = 1950; -- شاطئ الغرام
UPDATE movies SET release_date = '1938-10-10' WHERE title = 'شيء من لا شيء' AND year = 1938; -- شيء من لا شيء
UPDATE movies SET release_date = '1955-04-11' WHERE title = 'قلبى يهواك' AND year = 1955; -- قلبى يهواك
UPDATE movies SET release_date = '1947-11-10' WHERE title = 'أبو زيد الهلالي' AND year = 1947; -- أبو زيد الهلالي
UPDATE movies SET release_date = '1946-11-11' WHERE title = 'يوم في العالي' AND year = 1946; -- يوم في العالي
UPDATE movies SET release_date = '1953-01-19' WHERE title = 'السر في بير' AND year = 1953; -- السر في بير
UPDATE movies SET release_date = '1955-12-24' WHERE title = 'دعونى اعيش' AND year = 1955; -- دعونى اعيش
UPDATE movies SET release_date = '1948-10-10' WHERE title = 'القاتل' AND year = 1948; -- القاتل
UPDATE movies SET release_date = '1953-10-29' WHERE title = 'حرام عليك' AND year = 1953; -- حرام عليك
UPDATE movies SET release_date = '1942-06-07' WHERE title = 'الشريد' AND year = 1942; -- الشريد
UPDATE movies SET release_date = '1950-04-24' WHERE title = 'إلهام' AND year = 1950; -- إلهام
UPDATE movies SET release_date = '1948-09-27' WHERE title = 'المستقبل المجهول' AND year = 1948; -- المستقبل المجهول
UPDATE movies SET release_date = '1939-09-28' WHERE title = 'سلفني 3 جنيه' AND year = 1939; -- سلفني 3 جنيه
UPDATE movies SET release_date = '1953-10-26' WHERE title = 'الحرمان' AND year = 1953; -- الحرمان
UPDATE movies SET release_date = '1928-05-30' WHERE title = 'سعاد الغجرية' AND year = 1928; -- سعاد الغجرية
UPDATE movies SET release_date = '1947-01-01' WHERE title = 'البريمو' AND year = 1947; -- البريمو
UPDATE movies SET release_date = '1952-09-29' WHERE title = 'حياتي إنت' AND year = 1952; -- حياتي إنت
UPDATE movies SET release_date = '2023-12-21' WHERE title = 'أبو نسب' AND year = 2023; -- أبو نسب
UPDATE movies SET release_date = '2023-02-08' WHERE title = 'الحب بتفاصيله' AND year = 2023; -- الحب بتفاصيله
UPDATE movies SET release_date = '1947-12-15' WHERE title = 'فاطمة' AND year = 1947; -- فاطمة
UPDATE movies SET release_date = '1950-02-13' WHERE title = 'أختى ستيتة' AND year = 1950; -- أختى ستيتة
UPDATE movies SET release_date = '1928-10-22' WHERE title = 'البحر بيضحك' AND year = 1928; -- البحر بيضحك
UPDATE movies SET release_date = '1938-03-03' WHERE title = 'أنا طبعي كده' AND year = 1938; -- أنا طبعي كده
UPDATE movies SET release_date = '1954-10-31' WHERE title = 'ارحم  دموعي' AND year = 1954; -- ارحم  دموعي
UPDATE movies SET release_date = '1942-01-03' WHERE title = 'ليلة الفرح' AND year = 1942; -- ليلة الفرح
UPDATE movies SET release_date = '1952-04-17' WHERE title = 'شمشون  ولبلب' AND year = 1952; -- شمشون  ولبلب
UPDATE movies SET release_date = '1947-01-01' WHERE title = 'خاتم سليمان' AND year = 1947; -- خاتم سليمان
UPDATE movies SET release_date = '1946-12-30' WHERE title = 'رجل المستقبل' AND year = 1946; -- رجل المستقبل
UPDATE movies SET release_date = '1952-05-12' WHERE title = 'مصري في لبنان' AND year = 1952; -- مصري في لبنان
UPDATE movies SET release_date = '1953-02-23' WHERE title = 'قطار الليل' AND year = 1953; -- قطار الليل
UPDATE movies SET release_date = '1934-02-08' WHERE title = 'عيون ساحرة' AND year = 1934; -- عيون ساحرة
UPDATE movies SET release_date = '1939-02-27' WHERE title = 'ليالى القاهرة' AND year = 1939; -- ليالى القاهرة
UPDATE movies SET release_date = '1937-12-30' WHERE title = 'وراء الستار' AND year = 1937; -- وراء الستار
UPDATE movies SET release_date = '1950-07-14' WHERE title = 'ليلة الدخلة' AND year = 1950; -- ليلة الدخلة
UPDATE movies SET release_date = '1955-10-03' WHERE title = 'في سبيل الحب' AND year = 1955; -- في سبيل الحب
UPDATE movies SET release_date = '1948-05-24' WHERE title = 'فتنة' AND year = 1948; -- فتنة
UPDATE movies SET release_date = '1935-01-02' WHERE title = 'الضحايا' AND year = 1935; -- الضحايا
UPDATE movies SET release_date = '1946-08-19' WHERE title = 'عواصف' AND year = 1946; -- عواصف
UPDATE movies SET release_date = '1946-01-01' WHERE title = 'بنت الشرق' AND year = 1946; -- بنت الشرق
UPDATE movies SET release_date = '1951-03-12' WHERE title = 'فيروز هانم' AND year = 1951; -- فيروز هانم
UPDATE movies SET release_date = '1951-10-07' WHERE title = 'عاصفة في الربيع' AND year = 1951; -- عاصفة في الربيع
UPDATE movies SET release_date = '1927-11-16' WHERE title = 'ليلى' AND year = 1927; -- ليلى
UPDATE movies SET release_date = '1952-02-21' WHERE title = 'الحب بهدلة' AND year = 1952; -- الحب بهدلة
UPDATE movies SET release_date = '1949-09-26' WHERE title = 'صاحبة الملاليم' AND year = 1949; -- صاحبة الملاليم
UPDATE movies SET release_date = '1941-03-20' WHERE title = 'ألف ليلة وليلة' AND year = 1941; -- ألف ليلة وليلة
UPDATE movies SET release_date = '1935-12-12' WHERE title = 'عنتر أفندي' AND year = 1935; -- عنتر أفندي
UPDATE movies SET release_date = '1948-05-15' WHERE title = 'نرجس' AND year = 1948; -- نرجس
UPDATE movies SET release_date = '1936-10-29' WHERE title = 'خفير الدرك' AND year = 1936; -- خفير الدرك
UPDATE movies SET release_date = '1951-10-01' WHERE title = 'أولادي' AND year = 1951; -- أولادي
UPDATE movies SET release_date = '1945-04-23' WHERE title = 'بين نارين' AND year = 1945; -- بين نارين
UPDATE movies SET release_date = '1945-01-02' WHERE title = 'السوق السوداء' AND year = 1945; -- السوق السوداء
UPDATE movies SET release_date = '1946-02-25' WHERE title = 'لعبة الست' AND year = 1946; -- لعبة الست
UPDATE movies SET release_date = '1953-09-13' WHERE title = 'إبن للإيجار' AND year = 1953; -- إبن للإيجار
UPDATE movies SET release_date = '2023-02-09' WHERE title = 'جروب الماميز' AND year = 2023; -- جروب الماميز
UPDATE movies SET release_date = '1954-10-04' WHERE title = 'الشيخ حسن' AND year = 1954; -- الشيخ حسن
UPDATE movies SET release_date = '1929-05-01' WHERE title = 'غادة الصحراء' AND year = 1929; -- غادة الصحراء
UPDATE movies SET release_date = '1949-01-10' WHERE title = 'كلام الناس' AND year = 1949; -- كلام الناس
UPDATE movies SET release_date = '1942-11-26' WHERE title = 'لو كنت غني' AND year = 1942; -- لو كنت غني
UPDATE movies SET release_date = '1955-03-21' WHERE title = 'إسماعيل يس يقابل ريا وسكينة' AND year = 1955; -- إسماعيل يس يقابل ريا وسكينة
UPDATE movies SET release_date = '1941-09-14' WHERE title = 'صلاح الدين الأيوبي' AND year = 1941; -- صلاح الدين الأيوبي
UPDATE movies SET release_date = '1935-01-01' WHERE title = 'الدكتور فرحات' AND year = 1935; -- الدكتور فرحات
UPDATE movies SET release_date = '1945-07-23' WHERE title = 'حسن وحسن' AND year = 1945; -- حسن وحسن
UPDATE movies SET release_date = '1955-05-23' WHERE title = 'الحبيب المجهول' AND year = 1955; -- الحبيب المجهول
UPDATE movies SET release_date = '1953-03-21' WHERE title = 'فاعل خير' AND year = 1953; -- فاعل خير
UPDATE movies SET release_date = '1954-07-03' WHERE title = 'الآنسة حنفي' AND year = 1954; -- الآنسة حنفي
UPDATE movies SET release_date = '1954-11-01' WHERE title = 'عزيزة' AND year = 1954; -- عزيزة
UPDATE movies SET release_date = '1944-04-24' WHERE title = 'عريس الهنا' AND year = 1944; -- عريس الهنا
UPDATE movies SET release_date = '1934-05-17' WHERE title = 'المندوبان' AND year = 1934; -- المندوبان
UPDATE movies SET release_date = '1955-01-22' WHERE title = 'عرايس فى المزاد' AND year = 1955; -- عرايس فى المزاد
UPDATE movies SET release_date = '1943-04-19' WHERE title = 'وادي النجوم' AND year = 1943; -- وادي النجوم
UPDATE movies SET release_date = '1950-11-06' WHERE title = 'حبايبي كتير' AND year = 1950; -- حبايبي كتير
UPDATE movies SET release_date = '1946-12-16' WHERE title = 'عدو المرأة' AND year = 1946; -- عدو المرأة
UPDATE movies SET release_date = '1945-05-11' WHERE title = 'ليلى بنت الفقراء' AND year = 1945; -- ليلى بنت الفقراء
UPDATE movies SET release_date = '1950-09-18' WHERE title = 'غرام راقصة' AND year = 1950; -- غرام راقصة
UPDATE movies SET release_date = '1949-07-18' WHERE title = 'هدى' AND year = 1949; -- هدى
UPDATE movies SET release_date = '1952-11-10' WHERE title = 'غلطة أب' AND year = 1952; -- غلطة أب
UPDATE movies SET release_date = '1933-04-06' WHERE title = 'أولاد مصر' AND year = 1933; -- أولاد مصر
UPDATE movies SET release_date = '1944-04-03' WHERE title = 'ابنتي' AND year = 1944; -- ابنتي
UPDATE movies SET release_date = '1944-10-19' WHERE title = 'ابن الحداد' AND year = 1944; -- ابن الحداد
UPDATE movies SET release_date = '1937-11-18' WHERE title = 'الرياضي' AND year = 1937; -- الرياضي
UPDATE movies SET release_date = '1944-01-03' WHERE title = 'يسقط الحب' AND year = 1944; -- يسقط الحب
UPDATE movies SET release_date = '1953-03-23' WHERE title = 'قلبي على ولدي' AND year = 1953; -- قلبي على ولدي
UPDATE movies SET release_date = '1950-01-01' WHERE title = 'سيبوني أغني' AND year = 1950; -- سيبوني أغني
UPDATE movies SET release_date = '1952-03-11' WHERE title = 'آمنت بالله' AND year = 1952; -- آمنت بالله
UPDATE movies SET release_date = '1947-09-08' WHERE title = 'قبلني يا أبي' AND year = 1947; -- قبلني يا أبي
UPDATE movies SET release_date = '1940-11-28' WHERE title = 'الورشة' AND year = 1940; -- الورشة
UPDATE movies SET release_date = '1955-02-07' WHERE title = 'مدرسة البنات' AND year = 1955; -- مدرسة البنات
UPDATE movies SET release_date = '1952-05-01' WHERE title = 'سلوا قلبي' AND year = 1952; -- سلوا قلبي
UPDATE movies SET release_date = '1923-01-01' WHERE title = 'برسوم يبحث عن وظيفة' AND year = 1923; -- برسوم يبحث عن وظيفة
UPDATE movies SET release_date = '1950-10-02' WHERE title = 'كيد النساء' AND year = 1950; -- كيد النساء
UPDATE movies SET release_date = '1942-04-09' WHERE title = 'على مسرح الحياة' AND year = 1942; -- على مسرح الحياة
UPDATE movies SET release_date = '1943-10-18' WHERE title = 'نداء الدم' AND year = 1943; -- نداء الدم
UPDATE movies SET release_date = '1948-02-05' WHERE title = 'العقاب' AND year = 1948; -- العقاب
UPDATE movies SET release_date = '1948-01-26' WHERE title = 'عدل السماء' AND year = 1948; -- عدل السماء
UPDATE movies SET release_date = '1954-03-22' WHERE title = 'رسالة غرام' AND year = 1954; -- رسالة غرام
UPDATE movies SET release_date = '1944-09-21' WHERE title = 'كدب في كدب' AND year = 1944; -- كدب في كدب
UPDATE movies SET release_date = '1954-04-26' WHERE title = 'رقصة الوداع' AND year = 1954; -- رقصة الوداع
UPDATE movies SET release_date = '1937-01-02' WHERE title = 'العز بهدلة' AND year = 1937; -- العز بهدلة
UPDATE movies SET release_date = '1946-11-04' WHERE title = 'ملاك الرحمة' AND year = 1946; -- ملاك الرحمة
UPDATE movies SET release_date = '1949-12-12' WHERE title = 'شارع البهلوان' AND year = 1949; -- شارع البهلوان
UPDATE movies SET release_date = '1951-07-02' WHERE title = 'الحب في خطر' AND year = 1951; -- الحب في خطر
UPDATE movies SET release_date = '1945-02-01' WHERE title = 'المظاهر' AND year = 1945; -- المظاهر
UPDATE movies SET release_date = '1952-09-08' WHERE title = 'قدم الخير' AND year = 1952; -- قدم الخير
UPDATE movies SET release_date = '1938-01-02' WHERE title = 'التلغراف' AND year = 1938; -- التلغراف
UPDATE movies SET release_date = '1946-11-04' WHERE title = 'أم السعد' AND year = 1946; -- أم السعد
UPDATE movies SET release_date = '1948-04-11' WHERE title = 'شمشون الجبار' AND year = 1948; -- شمشون الجبار
UPDATE movies SET release_date = '1943-12-06' WHERE title = 'ماجدة' AND year = 1943; -- ماجدة
UPDATE movies SET release_date = '1952-08-08' WHERE title = 'عايزة أتجوز' AND year = 1952; -- عايزة أتجوز
UPDATE movies SET release_date = '1935-12-23' WHERE title = 'دموع الحب' AND year = 1935; -- دموع الحب
UPDATE movies SET release_date = '1950-04-10' WHERE title = 'طريق الشوك' AND year = 1950; -- طريق الشوك
UPDATE movies SET release_date = '1948-01-01' WHERE title = 'بلبل أفندي' AND year = 1948; -- بلبل أفندي
UPDATE movies SET release_date = '1945-12-24' WHERE title = 'بنات الريف' AND year = 1945; -- بنات الريف
UPDATE movies SET release_date = '1942-05-18' WHERE title = 'المتهمة' AND year = 1942; -- المتهمة
UPDATE movies SET release_date = '1952-12-08' WHERE title = 'أنا وحدي' AND year = 1952; -- أنا وحدي
UPDATE movies SET release_date = '1945-10-14' WHERE title = 'الحظ السعيد' AND year = 1945; -- الحظ السعيد
UPDATE movies SET release_date = '1949-03-28' WHERE title = 'المصري أفندي' AND year = 1949; -- المصري أفندي
UPDATE movies SET release_date = '1953-07-06' WHERE title = 'كلمة الحق' AND year = 1953; -- كلمة الحق
UPDATE movies SET release_date = '1947-03-31' WHERE title = 'غدر وعذاب' AND year = 1947; -- غدر وعذاب
UPDATE movies SET release_date = '1945-10-25' WHERE title = 'الفنان العظيم' AND year = 1945; -- الفنان العظيم
UPDATE movies SET release_date = '1944-10-05' WHERE title = 'نادوجا' AND year = 1944; -- نادوجا
UPDATE movies SET release_date = '1948-02-26' WHERE title = 'سجى الليل' AND year = 1948; -- سجى الليل
UPDATE movies SET release_date = '1945-12-03' WHERE title = 'هذا جناه أبي' AND year = 1945; -- هذا جناه أبي
UPDATE movies SET release_date = '1955-12-12' WHERE title = 'دموع في الليل' AND year = 1955; -- دموع في الليل
UPDATE movies SET release_date = '1952-01-01' WHERE title = 'البيت السعيد' AND year = 1952; -- البيت السعيد
UPDATE movies SET release_date = '1953-11-02' WHERE title = 'اللص الشريف' AND year = 1953; -- اللص الشريف
UPDATE movies SET release_date = '1944-02-14' WHERE title = 'طاقية الإخفاء' AND year = 1944; -- طاقية الإخفاء
UPDATE movies SET release_date = '1940-02-29' WHERE title = 'فتاة متمردة' AND year = 1940; -- فتاة متمردة
UPDATE movies SET release_date = '1945-01-03' WHERE title = 'قبلة في لبنان' AND year = 1945; -- قبلة في لبنان
UPDATE movies SET release_date = '1944-11-13' WHERE title = 'حبابة' AND year = 1944; -- حبابة
UPDATE movies SET release_date = '1949-07-25' WHERE title = 'فاطمة وماريكا وراشيل' AND year = 1949; -- فاطمة وماريكا وراشيل
UPDATE movies SET release_date = '1952-11-03' WHERE title = 'حبيب قلبي' AND year = 1952; -- حبيب قلبي
UPDATE movies SET release_date = '1950-07-10' WHERE title = 'الآنسة ماما' AND year = 1950; -- الآنسة ماما
UPDATE movies SET release_date = '1948-03-29' WHERE title = 'حب وجنون' AND year = 1948; -- حب وجنون
UPDATE movies SET release_date = '1935-02-26' WHERE title = 'شجرة الدر' AND year = 1935; -- شجرة الدر
UPDATE movies SET release_date = '1935-04-03' WHERE title = 'شالوم الترجمان' AND year = 1935; -- شالوم الترجمان
UPDATE movies SET release_date = '1930-11-25' WHERE title = 'الكوكايين (الهاوية)' AND year = 1930; -- الكوكايين (الهاوية)
UPDATE movies SET release_date = '1948-10-04' WHERE title = 'الروح والجسد' AND year = 1948; -- الروح والجسد
UPDATE movies SET release_date = '1953-04-12' WHERE title = 'الشك القاتل' AND year = 1953; -- الشك القاتل
UPDATE movies SET release_date = '1938-01-24' WHERE title = 'يحيا الحب' AND year = 1938; -- يحيا الحب
UPDATE movies SET release_date = '1939-01-05' WHERE title = 'فتش عن المرأة' AND year = 1939; -- فتش عن المرأة
UPDATE movies SET release_date = '1939-01-19' WHERE title = 'ثمن السعادة' AND year = 1939; -- ثمن السعادة
UPDATE movies SET release_date = '1954-02-15' WHERE title = 'أنا الحب' AND year = 1954; -- أنا الحب
UPDATE movies SET release_date = '2023-05-10' WHERE title = 'تحت الضغط' AND year = 2023; -- تحت الضغط
UPDATE movies SET release_date = '1947-04-21' WHERE title = 'القاهرة بغداد' AND year = 1947; -- القاهرة بغداد
UPDATE movies SET release_date = '1934-03-27' WHERE title = 'الاتهام' AND year = 1934; -- الاتهام
UPDATE movies SET release_date = '1929-01-01' WHERE title = 'جهنم في الرمال' AND year = 1929; -- جهنم في الرمال
UPDATE movies SET release_date = '1947-02-26' WHERE title = 'قلبي وسيفي' AND year = 1947; -- قلبي وسيفي
UPDATE movies SET release_date = '1949-09-26' WHERE title = 'لهاليبو' AND year = 1949; -- لهاليبو
UPDATE movies SET release_date = '1952-03-17' WHERE title = 'غضب الوالدين' AND year = 1952; -- غضب الوالدين
UPDATE movies SET release_date = '1947-12-01' WHERE title = 'صباح الخير' AND year = 1947; -- صباح الخير
UPDATE movies SET release_date = '1952-07-28' WHERE title = 'عشرة بلدي' AND year = 1952; -- عشرة بلدي
UPDATE movies SET release_date = '1950-04-10' WHERE title = 'الأفوكاتو مديحة' AND year = 1950; -- الأفوكاتو مديحة
UPDATE movies SET release_date = '1947-12-26' WHERE title = 'كانت ملاكا' AND year = 1947; -- كانت ملاكا
UPDATE movies SET release_date = '1952-04-28' WHERE title = 'على كيفك' AND year = 1952; -- على كيفك
UPDATE movies SET release_date = '1949-04-11' WHERE title = 'ست البيت' AND year = 1949; -- ست البيت
UPDATE movies SET release_date = '1933-01-23' WHERE title = 'كفرّى عن خطيئتك' AND year = 1933; -- كفرّى عن خطيئتك
UPDATE movies SET release_date = '1949-02-28' WHERE title = 'البيت الكبير' AND year = 1949; -- البيت الكبير
UPDATE movies SET release_date = '1946-10-13' WHERE title = 'الماضي المجهول' AND year = 1946; -- الماضي المجهول
UPDATE movies SET release_date = '1938-01-13' WHERE title = 'بنت الباشا المدير' AND year = 1938; -- بنت الباشا المدير
UPDATE movies SET release_date = '1945-04-26' WHERE title = 'القلب له واحد' AND year = 1945; -- القلب له واحد
UPDATE movies SET release_date = '1947-11-17' WHERE title = 'ابن عنتر' AND year = 1947; -- ابن عنتر
UPDATE movies SET release_date = '1951-02-19' WHERE title = 'مشغول بغيري' AND year = 1951; -- مشغول بغيري
UPDATE movies SET release_date = '1950-03-27' WHERE title = 'ساعة لقلبك' AND year = 1950; -- ساعة لقلبك
UPDATE movies SET release_date = '1955-02-07' WHERE title = 'عاشق الروح' AND year = 1955; -- عاشق الروح
UPDATE movies SET release_date = '1943-04-22' WHERE title = 'نداء القلب' AND year = 1943; -- نداء القلب
UPDATE movies SET release_date = '1928-12-05' WHERE title = 'فاجعة فوق الهرم' AND year = 1928; -- فاجعة فوق الهرم
UPDATE movies SET release_date = '1954-08-02' WHERE title = 'دايماً معاك' AND year = 1954; -- دايماً معاك
UPDATE movies SET release_date = '1926-06-28' WHERE title = 'نداء الرب' AND year = 1926; -- نداء الرب
UPDATE movies SET release_date = '1947-03-28' WHERE title = 'أمل ضائع' AND year = 1947; -- أمل ضائع
UPDATE movies SET release_date = '1933-03-27' WHERE title = 'عندما تحب المرأة' AND year = 1933; -- عندما تحب المرأة
UPDATE movies SET release_date = '1951-04-23' WHERE title = 'فى الهوا سوا' AND year = 1951; -- فى الهوا سوا
UPDATE movies SET release_date = '1953-05-12' WHERE title = 'حكم الزمان' AND year = 1953; -- حكم الزمان
UPDATE movies SET release_date = '1951-11-29' WHERE title = 'فايق ورايق' AND year = 1951; -- فايق ورايق
UPDATE movies SET release_date = '1936-02-09' WHERE title = 'زوجة بالنيابة' AND year = 1936; -- زوجة بالنيابة
UPDATE movies SET release_date = '1942-01-01' WHERE title = 'أحب الغلط' AND year = 1942; -- أحب الغلط
UPDATE movies SET release_date = '1951-04-12' WHERE title = 'المعلم بلبل' AND year = 1951; -- المعلم بلبل
UPDATE movies SET release_date = '1948-05-03' WHERE title = 'خلود' AND year = 1948; -- خلود
UPDATE movies SET release_date = '1945-04-26' WHERE title = 'الجنس اللطيف' AND year = 1945; -- الجنس اللطيف
UPDATE movies SET release_date = '1946-01-01' WHERE title = 'إكسبريس الحب' AND year = 1946; -- إكسبريس الحب
UPDATE movies SET release_date = '1949-05-19' WHERE title = 'أرواح هائمة' AND year = 1949; -- أرواح هائمة
UPDATE movies SET release_date = '1955-11-06' WHERE title = 'قصة حبي' AND year = 1955; -- قصة حبي
UPDATE movies SET release_date = '1936-01-01' WHERE title = 'بنكنوت' AND year = 1936; -- بنكنوت
UPDATE movies SET release_date = '1950-04-14' WHERE title = 'مغامرات خضرة' AND year = 1950; -- مغامرات خضرة
UPDATE movies SET release_date = '1947-01-01' WHERE title = 'زهرة السوق' AND year = 1947; -- زهرة السوق
UPDATE movies SET release_date = '1955-01-17' WHERE title = 'فجر' AND year = 1955; -- فجر
UPDATE movies SET release_date = '1940-11-14' WHERE title = 'أصحاب العقول' AND year = 1940; -- أصحاب العقول
UPDATE movies SET release_date = '1954-03-04' WHERE title = 'العمر واحد' AND year = 1954; -- العمر واحد
UPDATE movies SET release_date = '1949-03-14' WHERE title = 'نص الليل' AND year = 1949; -- نص الليل
UPDATE movies SET release_date = '1939-12-28' WHERE title = 'العودة إلى الريف' AND year = 1939; -- العودة إلى الريف
UPDATE movies SET release_date = '1928-01-01' WHERE title = 'صانع القباقيب' AND year = 1928; -- صانع القباقيب
UPDATE movies SET release_date = '1923-07-11' WHERE title = 'في بلاد توت عنخ آمون' AND year = 1923; -- في بلاد توت عنخ آمون
UPDATE movies SET release_date = '1932-08-29' WHERE title = 'مصطفى أو الساحر الصغير' AND year = 1932; -- مصطفى أو الساحر الصغير
COMMIT;
