from __future__ import annotations

import csv
import re
import sqlite3
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "egyptian_movies.csv"
DB_PATH = ROOT / "elfilm.db"
MIGRATION_PATHS = [
    ROOT / "migrations" / "005_backfill_release_dates.sql",
    ROOT / "site" / "migrations" / "005_backfill_release_dates.sql",
]


def normalize(value: str | None) -> str:
    text = (value or "").strip().lower()
    text = re.sub(r"\s+", " ", text)
    text = text.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا").replace("ى", "ي").replace("ة", "ه")
    text = re.sub(r"[\u064B-\u0652]", "", text)
    text = text.replace("ـ", "")
    return text


@dataclass(frozen=True)
class MovieRow:
    id: str
    title_ar: str | None
    title_en: str | None
    year: int | None


def load_movies() -> list[MovieRow]:
    with sqlite3.connect(DB_PATH) as con:
        cur = con.cursor()
        rows = cur.execute("SELECT id, title_ar, title_en, year FROM movies").fetchall()
    return [MovieRow(*row) for row in rows]


def build_indexes(movies: list[MovieRow]) -> tuple[dict[tuple[str, str], list[MovieRow]], dict[tuple[str, str], list[MovieRow]]]:
    exact: dict[tuple[str, str], list[MovieRow]] = {}
    normalized: dict[tuple[str, str], list[MovieRow]] = {}
    for movie in movies:
        year = str(movie.year or "")
        for value in (movie.title_ar, movie.title_en):
            if not value:
                continue
            exact.setdefault((value.strip().lower(), year), []).append(movie)
            normalized.setdefault((normalize(value), year), []).append(movie)
    return exact, normalized


def choose_movie(
    exact_index: dict[tuple[str, str], list[MovieRow]],
    normalized_index: dict[tuple[str, str], list[MovieRow]],
    arabic_title: str,
    english_title: str,
    year: str,
) -> tuple[MovieRow, str] | None:
    for title in (arabic_title, english_title):
        if not title:
            continue
        candidates = exact_index.get((title.strip().lower(), year), [])
        if len(candidates) == 1:
            return candidates[0], title

    for title in (arabic_title, english_title):
        if not title:
            continue
        candidates = normalized_index.get((normalize(title), year), [])
        if len(candidates) == 1:
            return candidates[0], title

    return None


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def generate_updates() -> tuple[list[tuple[str, str, str]], list[dict[str, str]]]:
    movies = load_movies()
    exact_index, normalized_index = build_indexes(movies)

    updates: list[tuple[str, str, str]] = []
    seen_ids: set[str] = set()
    skipped: list[dict[str, str]] = []

    with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            release_date = (row.get("Release_Date") or "").strip()
            if not release_date:
                continue

            year = release_date[:4]
            arabic_title = (row.get("Original_Title") or "").strip()
            english_title = (row.get("Title") or "").strip()
            chosen = choose_movie(exact_index, normalized_index, arabic_title, english_title, year)

            if chosen is None:
                skipped.append(
                    {
                        "id": row.get("ID", ""),
                        "title": english_title,
                        "original_title": arabic_title,
                        "release_date": release_date,
                    }
                )
                continue

            movie, matched_title = chosen

            if movie.id in seen_ids:
                continue

            seen_ids.add(movie.id)
            updates.append((matched_title, release_date, year))

    return updates, skipped


def write_migration(updates: list[tuple[str, str, str]]) -> None:
    statements = [
        "-- Backfill release_date values from egyptian_movies.csv using exact year-aware title matches.",
        "-- Generated by scripts/generate_release_date_backfill.py.",
        "",
        "BEGIN;",
    ]

    for movie_title, release_date, year in updates:
        statements.append(
            f"UPDATE movies SET release_date = '{sql_escape(release_date)}' WHERE title = '{sql_escape(movie_title)}' AND year = {year}; -- {sql_escape(movie_title)}"
        )

    statements.extend(["COMMIT;", ""])
    content = "\n".join(statements)

    for path in MIGRATION_PATHS:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    updates, skipped = generate_updates()
    write_migration(updates)

    print(f"Generated {len(updates)} release_date updates.")
    print(f"Skipped {len(skipped)} rows without a unique title/year match.")
    if skipped:
        print("First skipped rows:")
        for row in skipped[:10]:
            print({k: row[k] for k in ("id", "release_date", "title") if row.get(k)})


if __name__ == "__main__":
    main()
